### ISSUE TITLE
Remove oppressive words from code

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataArticleBundle#174]
## Feature Request

We should avoid terms like *blacklist*, *whitliste*, *master*, *slave*, ... and use more tech-related words like *blocklist*, *primary*, *secondary*,...

In this repo, we use the term *whitelist* which could be replaced with *allowlist*:
https://github.com/sonata-project/SonataArticleBundle/blob/1.x/src/DependencyInjection/SonataArticleExtension.php#L71

**Comment by VincentLanglet** [comment]
This bundle is abandoned
