### ISSUE TITLE
docs are not linked on the website

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataArticleBundle#26]
the result, when clicking the link in the README is:

https://sonata-project.org/bundles/article

@rande can you please link the ArticleBundle in the list of the "Feature bundles"?

thank you

**Comment by OskarStark** [comment]
ping @rande

**Comment by OskarStark** [comment]
@Soullivaneuh maybe you can check this bundle, too?

**Comment by core23** [comment]
Can't we do this ourself on the gitlab repo or via the admin panel?

**Comment by soullivaneuh** [comment]
@core23 None of them. I have to deal with the doc builder first.

**Comment by Wharenn** [comment]
Hi @sonata-project/contributors, I think we can close this issue 🎉 
https://sonata-project.org/bundles/article/master/doc/index.html

**Comment by OskarStark** [comment]
Thanks
