### ISSUE TITLE
Fragment deletion is not flagged anymore

### ISSUE THREAD

**Issue by srascar** [sonata-project/SonataArticleBundle#278]
#### Sonata packages

```
sonata-project/admin-bundle            3.88.0
sonata-project/article-bundle            1.5.0
```

## Subject
The support for the `_delete` field has been lost when submitting the fragment form field

## Steps to reproduce
* Create an ArticleAdmin
* Create a fragments field of type collection
* Edit the article to add a fragment
* Remove the fragment and submit the form
* Dump the value of `_delete` in `pre_bind_data_callback`
ex:
```
$formMapper
            ->add('fragments', CollectionType::class, [
                'constraints'  => [new Valid()],
                'by_reference' => false,
                'label'        => false,
                'pre_bind_data_callback' => function ($value) {
                    dump($value);

                    // ...
```
* 

## Expected results
When the fragment has beed deleted, $value where the key `id` corresponds to the deleted fragment should contain a `_delete` key

## Actual results
$value where the key `id` corresponds to the deleted fragment is never received

**Comment by VincentLanglet** [comment]
> The support for the `_delete` field has been lost when submitting the fragment form field

Do you know in which version ?

**Comment by srascar** [comment]
It happened on tag 1.3
https://github.com/sonata-project/SonataArticleBundle/commit/2a52eeda78328ef22ca819ec5210f5fdbb702d93#diff-ae864fbf4f9062ada8c1e8d888855a8f8b622efb0066e1ddcf7a0cf9d63b96e8L188

**Comment by VincentLanglet** [comment]
Do you know how to fix this ? Can you do the PR ? :)

**Comment by srascar** [comment]
Started https://github.com/sonata-project/SonataArticleBundle/pull/280
