### ISSUE TITLE
Invalid include of a JS within a template

### ISSUE THREAD

**Issue by srascar** [sonata-project/SonataArticleBundle#279]
## Subject
There should be not hard include of a js within a template.
Every time the template is called, the js is reloaded.
Also the path might conflict with the one defined in the `webpack.config`

The file should instead be compiled alongside the other assets using Encore.

https://github.com/sonata-project/SonataArticleBundle/blob/d6f0e276b1e15b477e559a8b3b241771c0544441/src/Resources/views/FragmentAdmin/edit_collection_fragment.html.twig#L32

**Comment by VincentLanglet** [comment]
This bundle is abandoned
