### ISSUE TITLE
Back Office Title should contain the empty_data option

### ISSUE THREAD

**Issue by srascar** [sonata-project/SonataArticleBundle#283]
The declaration of the `backofficeTitle` field should include the `empty_data` option.
If not, this conflicts with the entity type declaration.

ex:
```
$formMapper->add('backofficeTitle', TextType::class, [
    'empty_data' => ''
]);
```

## Expected 
* On form submit, when an empty string is sent, the property should be mapped

## Actual

```
Expected argument of type "string", "null" given at property path "backofficeTitle".
```

https://github.com/sonata-project/SonataArticleBundle/blob/bfcb250f097b9f4a3971a9a23bb04ba6fe6fdb65/src/FragmentService/AbstractFragmentService.php#L49

**Comment by VincentLanglet** [comment]
Shouldn't the field be required ?

**Comment by srascar** [comment]
The field is required but this check is made by validators. That means the entity property is set before and that raises an  exception in the property accessor

**Comment by VincentLanglet** [comment]
Do you mind making the PR ?

**Comment by srascar** [comment]
https://github.com/sonata-project/SonataArticleBundle/pull/284
