### ISSUE TITLE
ArticleAdmin

### ISSUE THREAD

**Issue by qsomazzi** [sonata-project/SonataArticleBundle#4]
## Subject

Should we make the class Final ? Abstract ? 
Only some methods final ? Other ?

https://github.com/sonata-project/SonataArticleBundle/pull/2#discussion_r70644514

**Comment by OskarStark** [comment]
any idea @greg0ire ?

**Comment by greg0ire** [comment]
I think requiring people to extend base classes from a package should be avoided if possible. Composition should be preferred over inheritance. Implementing interfaces, on the other hand, looks like a good idea.
