### ISSUE TITLE
First tagged release?

### ISSUE THREAD

**Issue by Wharenn** [sonata-project/SonataArticleBundle#52]
Hi,

We're using this dependency for quite a while with no tag to refer to. According to last months history on this bundle, it seems there is no incoming features nor unresolved bugs, it seems a perfect time to tag!

Is there any plan to create a first tagged release soon? If some work is still to be done before tagging, maybe we should list it :-)

Thanks

**Comment by OskarStark** [comment]
I totally agree!
@Soullivaneuh can you help?

**Comment by core23** [comment]
There is still some stuff to do, so what about a `0.1` release?

**Comment by Wharenn** [comment]
Yes, that would be a first step ;)
I'm curious about what todo stuff are you referring to? The issues tagged as enhancements?

**Comment by greg0ire** [comment]
The branch is aliased to `1.x-dev`, that means you have to change that if you want a `0.1` release.

**Comment by Wharenn** [comment]
Hi guys, can we set up a todo list to reach a first release of this bundle ?

**Comment by mazsudo** [comment]
:+1: @Wharenn 

@sonata-project/release-managers, IMO major stuffs to do before a 0.1 release are:
- link the ArticleBundle in the list of the "Feature bundles" (see #26 )
- add (a lot) unit tests (will try to add some this week)

do you see anything else?

**Comment by Wharenn** [comment]
Hi @bmaziere, I can help on the improvement of coverage. Do you want to split the scope?

**Comment by mazsudo** [comment]
with pleasure @Wharenn . I started on DependencyInjection folder. you can take any other ;)

**Comment by mazsudo** [comment]
hi @sonata-project/release-managers. It seems coverage has been well improved (not perfect but in progress). What can be done now to move forward and reach a 0.1 release? 
Remaining task IMO is `link the ArticleBundle in the list of the "Feature bundles" (see #26 )` :

- who can do that?
- do you see anything else?

**Comment by OskarStark** [comment]
IMO we can tag `1.0` and make the docs available on our website

**Comment by greg0ire** [comment]
I think symfony < 3.4 support should be dropped before the release

**Comment by kunicmarko20** [comment]
Agree with @greg0ire, also, checking if everything is final, see if something final is missing an interface, adding typehints and return types, removing useless comments.

**Comment by kunicmarko20** [comment]
namespace for twig and drop older version also

**Comment by OskarStark** [comment]
Maybe be should use a github project to write down what todo for the first release? So everybody gets an overview...

**Comment by qsomazzi** [comment]
We use symfony 3.4 and SonataArticleBundle, we can't drop it before the first release.

I don't understand why this is an issue to create a tag 1.0. This bundle is used and maintained by us. Let's get a first release out, we will improve it over time as we currently do.

**Comment by greg0ire** [comment]
Sure, go ahead

**Comment by kunicmarko20** [comment]
I don't think it is needed anymore, most of the stuff is done. 

:+1: from me to release this.

**Comment by core23** [comment]
Can we drop support for PHP 7.1, because the active support ends next month

We could also require the latest versions for the sonata deps:
https://github.com/sonata-project/SonataArticleBundle/blob/a833d06e2ce5831c5ef70239e01e459ece0306c0/composer.json#L18-L22

**Comment by kunicmarko20** [comment]
`because the active support ends next month` just because of this, probably no, also not sure what @sonata-project/ekino is using in prod, since they are mostly using this bundle.

**Comment by Wharenn** [comment]
Yeah, it would be nice to keep 7.1 for now ;)

**Comment by mazsudo** [comment]
👍 to keep 7.1 for now ;)
however, https://github.com/sonata-project/SonataArticleBundle/pull/89 is required at least for the first release (important fix on `src/Resources/config/doctrine/AbstractFragment.orm.xml`)

**Comment by nanofelis** [comment]
#89 has been merged, so I believe nothing stands in the way of the release now.

**Comment by kunicmarko20** [comment]
cc @greg0ire

**Comment by greg0ire** [comment]
Expect it on Saturday

**Comment by greg0ire** [comment]
Some dependencies are outdated:
```
imagine/imagine       v0.7.1  1.1.0  Image processing for PHP 5.3
jms/metadata          1.7.0   2.0.0  Class/method/property metadata management in PHP
jms/serializer        1.13.0  2.0.0  Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle 2.4.2   3.0.0  Allows you to easily serialize, and deserialize data of any complexity
kriswallsmith/buzz    v0.16.1 0.17.2 Lightweight HTTP client
```

**Comment by greg0ire** [comment]
But it only seems to be the fault of the media bundle

**Comment by greg0ire** [comment]
Closing :)
