### ISSUE TITLE
Add doc

### ISSUE THREAD

**Issue by qsomazzi** [sonata-project/SonataArticleBundle#8]
## Subject

Add more doc

https://github.com/sonata-project/SonataArticleBundle/pull/2#issuecomment-234184110

**Comment by greg0ire** [comment]
A nice resource for this : http://www.writethedocs.org/guide/writing/beginners-guide-to-docs/#what-to-write

**Comment by greg0ire** [comment]
The doc should answer questions raised by @Filoz in #10

**Comment by OskarStark** [comment]
IMO we should close this issue

**Comment by jordisala1991** [comment]
Closing as docs are already there. Might be interesting to add issues of specific docs missing, but the general docs are there. We also have an issue to add those docs to the sonata webpage https://github.com/sonata-project/SonataArticleBundle/issues/26

If you feel this should remain open, ping me or directly reopen
